const products = [
     {
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/m/a/mackerel_whole_1.jpg",
          title: "Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          mrp: 375,
          weight: "500g",
          price: 99,
          desc: "The mackerel is one of the most abused fish by the local market as its often shined in ammonia given its very soft & decay prone nature. Our mackerels in comparison will actually look more tame but the taste will be nothing like what you have eaten in the local market - most of our customers have written to us as they rediscover the mackerel from their childhood days when things were fresh - if you experience this, please let us know",
          category: "Mutton",
          lignThroughMrp: "599.00",
          storageInstructions: "40% cold",
          marketedBy: "FCI",
          id: 1,
          cartQuantity: 0,
     },
     {
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/m/a/mackerel_whole_1.jpg",
          title: "Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          mrp: "375.00",
          weight: "500g",
          price: 99,
          desc: "The mackerel is one of the most abused fish by the local market as its often shined in ammonia given its very soft & decay prone nature. Our mackerels in comparison will actually look more tame but the taste will be nothing like what you have eaten in the local market - most of our customers have written to us as they rediscover the mackerel from their childhood days when things were fresh - if you experience this, please let us know",
          category: "Mutton",
          lignThroughMrp: "599.00",
          storageInstructions: "40% cold",
          marketedBy: "FCI",
          id: 4,
          cartQuantity: 0,
     },
     {
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/m/a/mackerel_whole_1.jpg",
          title: "Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          mrp: "375.00",
          weight: "500g",
          price: 99,
          desc: "The mackerel is one of the most abused fish by the local market as its often shined in ammonia given its very soft & decay prone nature. Our mackerels in comparison will actually look more tame but the taste will be nothing like what you have eaten in the local market - most of our customers have written to us as they rediscover the mackerel from their childhood days when things were fresh - if you experience this, please let us know",
          category: "Mutton",
          lignThroughMrp: "599.00",
          storageInstructions: "40% cold",
          marketedBy: "FCI",
          id: 5,
          cartQuantity: 2,
     },
     {
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/m/a/mackerel_whole_1.jpg",
          title: "Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          mrp: "375.00",
          weight: "500g",
          price: 99,
          desc: "The mackerel is one of the most abused fish by the local market as its often shined in ammonia given its very soft & decay prone nature. Our mackerels in comparison will actually look more tame but the taste will be nothing like what you have eaten in the local market - most of our customers have written to us as they rediscover the mackerel from their childhood days when things were fresh - if you experience this, please let us know",
          category: "Mutton",
          lignThroughMrp: "599.00",
          storageInstructions: "40% cold",
          marketedBy: "FCI",
          id: 6,
          cartQuantity: 0,
     },
     {
          title: " Fresh Indian Baasa / Pangasius - Boneless Fillet 250g Pack",
          category: "Mutton",
          mrp: "149.00 ",
          lignThroughMrp: "398.00",
          desc: "This true swadeshi product has rose coloured meat and is nothing like the frozen, many months old, bleached white Vietnam Baasa available in retail stores. Has a lot of tasty & healthy fish oil and doesn't really require extra oil for cooking",
          storageInstructions:
               "Store under refrigeration at 4°C or below, in hygienic conditions",
          marketedBy:
               "Freshalicious Super Bazaar Pvt. Ltd. No. 42, Chikkagubbi Village, Bangalore East Taluk, Bangalore Urban, Karnataka - 560077",
          weight: "250g",
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/i/n/indian_baasa_1.jpg",
          id: 2,
          cartQuantity: 1,
     },
     {
          title: " Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          category: "Mutton",
          mrp: "375.00",
          lignThroughMrp: "599.00",
          desc: "They say we are choosy with our meats - you will believe it when we tell you that we only serve the very premium young male goat approximately 6-8 months old with meat so tender that it will melt in your mouth. We apologise in advance to the non-goat eaters who may find the description gory, but our meat is simply the finest in town!",
          storageInstructions:
               "Store under refrigeration at 4°C or below, in hygienic conditions",
          marketedBy:
               "Freshalicious Super Bazaar Pvt. Ltd. No. 42, Chikkagubbi Village, Bangalore East Taluk, Bangalore Urban, Karnataka - 560077",
          weight: "250g",
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/p/r/premium_tender_goat_curry_cut.jpg",
          id: 3,
          cartQuantity: 1,
     },
     {
          title: " Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          category: "Mutton",
          mrp: "375.00",
          lignThroughMrp: "599.00",
          desc: "They say we are choosy with our meats - you will believe it when we tell you that we only serve the very premium young male goat approximately 6-8 months old with meat so tender that it will melt in your mouth. We apologise in advance to the non-goat eaters who may find the description gory, but our meat is simply the finest in town!",
          storageInstructions:
               "Store under refrigeration at 4°C or below, in hygienic conditions",
          marketedBy:
               "Freshalicious Super Bazaar Pvt. Ltd. No. 42, Chikkagubbi Village, Bangalore East Taluk, Bangalore Urban, Karnataka - 560077",
          weight: "250g",
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/p/r/premium_tender_goat_curry_cut.jpg",
          id: 7,
          cartQuantity: 0,
     },
     {
          title: " Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          category: "Mutton",
          mrp: "375.00",
          lignThroughMrp: "599.00",
          desc: "They say we are choosy with our meats - you will believe it when we tell you that we only serve the very premium young male goat approximately 6-8 months old with meat so tender that it will melt in your mouth. We apologise in advance to the non-goat eaters who may find the description gory, but our meat is simply the finest in town!",
          storageInstructions:
               "Store under refrigeration at 4°C or below, in hygienic conditions",
          marketedBy:
               "Freshalicious Super Bazaar Pvt. Ltd. No. 42, Chikkagubbi Village, Bangalore East Taluk, Bangalore Urban, Karnataka - 560077",
          weight: "250g",
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/p/r/premium_tender_goat_curry_cut.jpg",
          id: 8,
          cartQuantity: 0,
     },
     {
          title: " Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          category: "Mutton",
          mrp: "375.00",
          lignThroughMrp: "599.00",
          desc: "They say we are choosy with our meats - you will believe it when we tell you that we only serve the very premium young male goat approximately 6-8 months old with meat so tender that it will melt in your mouth. We apologise in advance to the non-goat eaters who may find the description gory, but our meat is simply the finest in town!",
          storageInstructions:
               "Store under refrigeration at 4°C or below, in hygienic conditions",
          marketedBy:
               "Freshalicious Super Bazaar Pvt. Ltd. No. 42, Chikkagubbi Village, Bangalore East Taluk, Bangalore Urban, Karnataka - 560077",
          weight: "250g",
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/p/r/premium_tender_goat_curry_cut.jpg",
          id: 9,
          cartQuantity: 0,
     },
     {
          title: " Premium Tender Goat - Curry Cut (480g to 500g Pack)",
          category: "Mutton",
          mrp: "375.00",
          lignThroughMrp: "599.00",
          desc: "They say we are choosy with our meats - you will believe it when we tell you that we only serve the very premium young male goat approximately 6-8 months old with meat so tender that it will melt in your mouth. We apologise in advance to the non-goat eaters who may find the description gory, but our meat is simply the finest in town!",
          storageInstructions:
               "Store under refrigeration at 4°C or below, in hygienic conditions",
          marketedBy:
               "Freshalicious Super Bazaar Pvt. Ltd. No. 42, Chikkagubbi Village, Bangalore East Taluk, Bangalore Urban, Karnataka - 560077",
          weight: "250g",
          image: "https://static.freshtohome.com/media/catalog/product/cache/93/image/400x267/18ae109e34f485bd0b0c075abec96b2e/p/r/premium_tender_goat_curry_cut.jpg",
          id: 10,
          cartQuantity: 0,
     },
];

module.exports = { products };
